=== renovatebot/renovate/data/abandonment-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Exceptions for abandoned packages",
  "description": "Community-sourced overrides for packages that appear abandoned but are still maintained",
  "type": "object",
  "definitions": {
    "datasourceConfig": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "properties": {
    "$schema": { "type": "string" },
    "artifactory": { "$ref": "#/definitions/datasourceConfig" },
    "aws-eks-addon": { "$ref": "#/definitions/datasourceConfig" },
    "aws-machine-image": { "$ref": "#/definitions/datasourceConfig" },
    "aws-rds": { "$ref": "#/definitions/datasourceConfig" },
    "azure-bicep-resource": { "$ref": "#/definitions/datasourceConfig" },
    "azure-pipelines-tasks": { "$ref": "#/definitions/datasourceConfig" },
    "bazel": { "$ref": "#/definitions/datasourceConfig" },
    "bitbucket-server-tags": { "$ref": "#/definitions/datasourceConfig" },
    "bitbucket-tags": { "$ref": "#/definitions/datasourceConfig" },
    "bitrise": { "$ref": "#/definitions/datasourceConfig" },
    "buildpacks-registry": { "$ref": "#/definitions/datasourceConfig" },
    "cdnjs": { "$ref": "#/definitions/datasourceConfig" },
    "clojure": { "$ref": "#/definitions/datasourceConfig" },
    "conan": { "$ref": "#/definitions/datasourceConfig" },
    "conda": { "$ref": "#/definitions/datasourceConfig" },
    "cpan": { "$ref": "#/definitions/datasourceConfig" },
    "crate": { "$ref": "#/definitions/datasourceConfig" },
    "custom": { "$ref": "#/definitions/datasourceConfig" },
    "dart": { "$ref": "#/definitions/datasourceConfig" },
    "dart-version": { "$ref": "#/definitions/datasourceConfig" },
    "deb": { "$ref": "#/definitions/datasourceConfig" },
    "deno": { "$ref": "#/definitions/datasourceConfig" },
    "devbox": { "$ref": "#/definitions/datasourceConfig" },
    "docker": { "$ref": "#/definitions/datasourceConfig" },
    "dotnet-version": { "$ref": "#/definitions/datasourceConfig" },
    "endoflife-date": { "$ref": "#/definitions/datasourceConfig" },
    "flutter-version": { "$ref": "#/definitions/datasourceConfig" },
    "galaxy": { "$ref": "#/definitions/datasourceConfig" },
    "galaxy-collection": { "$ref": "#/definitions/datasourceConfig" },
    "git-refs": { "$ref": "#/definitions/datasourceConfig" },
    "git-tags": { "$ref": "#/definitions/datasourceConfig" },
    "gitea-releases": { "$ref": "#/definitions/datasourceConfig" },
    "gitea-tags": { "$ref": "#/definitions/datasourceConfig" },
    "github-release-attachments": { "$ref": "#/definitions/datasourceConfig" },
    "github-releases": { "$ref": "#/definitions/datasourceConfig" },
    "github-runners": { "$ref": "#/definitions/datasourceConfig" },
    "github-tags": { "$ref": "#/definitions/datasourceConfig" },
    "gitlab-packages": { "$ref": "#/definitions/datasourceConfig" },
    "gitlab-releases": { "$ref": "#/definitions/datasourceConfig" },
    "gitlab-tags": { "$ref": "#/definitions/datasourceConfig" },
    "glasskube-packages": { "$ref": "#/definitions/datasourceConfig" },
    "go": { "$ref": "#/definitions/datasourceConfig" },
    "go-direct": { "$ref": "#/definitions/datasourceConfig" },
    "go-proxy": { "$ref": "#/definitions/datasourceConfig" },
    "golang-version": { "$ref": "#/definitions/datasourceConfig" },
    "gradle-version": { "$ref": "#/definitions/datasourceConfig" },
    "hackage": { "$ref": "#/definitions/datasourceConfig" },
    "helm": { "$ref": "#/definitions/datasourceConfig" },
    "hermit": { "$ref": "#/definitions/datasourceConfig" },
    "hex": { "$ref": "#/definitions/datasourceConfig" },
    "hexpm-bob": { "$ref": "#/definitions/datasourceConfig" },
    "java-version": { "$ref": "#/definitions/datasourceConfig" },
    "jenkins-plugins": { "$ref": "#/definitions/datasourceConfig" },
    "kubernetes-api": { "$ref": "#/definitions/datasourceConfig" },
    "maven": { "$ref": "#/definitions/datasourceConfig" },
    "node-version": { "$ref": "#/definitions/datasourceConfig" },
    "npm": { "$ref": "#/definitions/datasourceConfig" },
    "nuget": { "$ref": "#/definitions/datasourceConfig" },
    "orb": { "$ref": "#/definitions/datasourceConfig" },
    "packagist": { "$ref": "#/definitions/datasourceConfig" },
    "pod": { "$ref": "#/definitions/datasourceConfig" },
    "puppet-forge": { "$ref": "#/definitions/datasourceConfig" },
    "pypi": { "$ref": "#/definitions/datasourceConfig" },
    "python-version": { "$ref": "#/definitions/datasourceConfig" },
    "repology": { "$ref": "#/definitions/datasourceConfig" },
    "ruby-version": { "$ref": "#/definitions/datasourceConfig" },
    "rubygems": { "$ref": "#/definitions/datasourceConfig" },
    "sbt-package": { "$ref": "#/definitions/datasourceConfig" },
    "sbt-plugin": { "$ref": "#/definitions/datasourceConfig" },
    "terraform-module": { "$ref": "#/definitions/datasourceConfig" },
    "terraform-provider": { "$ref": "#/definitions/datasourceConfig" },
    "unity3d": { "$ref": "#/definitions/datasourceConfig" }
  },
  "additionalProperties": {
    "$ref": "#/definitions/datasourceConfig"
  }
}

=== renovatebot/renovate/lib/data/changelog-urls.json
{
  "$schema": "../../tools/schemas/changelog-urls-schema.json",
  "npm": {
    "babel-preset-react-app": "https://github.com/facebook/create-react-app/releases",
    "firebase": "https://firebase.google.com/support/release-notes/js",
    "flow-bin": "https://github.com/facebook/flow/blob/master/Changelog.md",
    "gatsby": "https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md",
    "react-native": "https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md",
    "sharp": "https://github.com/lovell/sharp/blob/main/docs/src/content/docs/changelog.md",
    "tailwindcss-classnames": "https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/CHANGELOG.md",
    "zone.js": "https://github.com/angular/angular/blob/master/packages/zone.js/CHANGELOG.md"
  },
  "pypi": {
    "beautifulsoup4": "https://git.launchpad.net/beautifulsoup/tree/CHANGELOG",
    "django-debug-toolbar": "https://django-debug-toolbar.readthedocs.io/en/latest/changes.html",
    "django-storages": "https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst",
    "flake8": "https://flake8.pycqa.org/en/latest/release-notes/index.html",
    "lxml": "https://git.launchpad.net/lxml/plain/CHANGES.txt",
    "mypy": "https://mypy.readthedocs.io/en/latest/changelog.html",
    "phonenumbers": "https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/HISTORY.md",
    "pycountry": "https://github.com/flyingcircusio/pycountry/blob/master/HISTORY.txt",
    "requests": "https://github.com/psf/requests/blob/master/HISTORY.md",
    "sqlalchemy": "https://docs.sqlalchemy.org/en/latest/changelog/",
    "uwsgi": "https://uwsgi-docs.readthedocs.io/en/latest/#release-notes"
  },
  "docker": {
    "gitlab/gitlab-ce": "https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/CHANGELOG.md",
    "gitlab/gitlab-runner": "https://gitlab.com/gitlab-org/gitlab-runner/-/blob/master/CHANGELOG.md",
    "google/cloud-sdk": "https://cloud.google.com/sdk/docs/release-notes",
    "neo4j": "https://neo4j.com/release-notes/",
    "whitesource/renovate": "https://github.com/whitesource/renovate-on-prem"
  },
  "maven": {
    "ch.qos.logback:logback-access": "https://logback.qos.ch/news.html",
    "ch.qos.logback:logback-classic": "https://logback.qos.ch/news.html",
    "ch.qos.logback:logback-core": "https://logback.qos.ch/news.html",
    "org.slf4j:jcl-over-slf4j": "https://www.slf4j.org/news.html",
    "org.slf4j:jul-over-slf4j": "https://www.slf4j.org/news.html",
    "org.slf4j:jul-to-slf4j": "https://www.slf4j.org/news.html",
    "org.slf4j:log4j-over-slf4j": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-android": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-api": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-bom": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-ext": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-jcl": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-jdk-platform-logging": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-migrator": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-nop": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-reload4j": "https://www.slf4j.org/news.html",
    "org.slf4j:slf4j-simple": "https://www.slf4j.org/news.html"
  },
  "nuget": {
    "Scalar.AspNetCore": "https://github.com/scalar/scalar/blob/main/integrations/aspnetcore/CHANGELOG.md",
    "Scalar.AspNetCore.Microsoft": "https://github.com/scalar/scalar/blob/main/integrations/aspnetcore/CHANGELOG.md",
    "Scalar.AspNetCore.Swashbuckle": "https://github.com/scalar/scalar/blob/main/integrations/aspnetcore/CHANGELOG.md"
  }
}
